### ISSUE TITLE
Missing server.js

### ISSUE THREAD

**Issue by tinchoz49** [mattkrick/fast-rtc-swarm#1]
Hi @mattkrick, how are you?

I think you forget to publish the `server.js` on NPM. 

https://github.com/mattkrick/fast-rtc-swarm/blob/master/package.json#L17

**Comment by mattkrick** [comment]
hi @tinchoz49, you're absolutely right! Now that Chrome 69 has landed with support for `unified-plan` (v1.0 stage 3) I'm rewriting it with support for audio/video & should have something up within the next couple days. I'm also adding support for uWS, since it uses a different structure for server clients.

In the meantime, feel free to copy the code from src/server.

**Comment by tinchoz49** [comment]
Hi @mattkrick ! that's great :+1: ! 

Also, I don't know if you have plans to add support for duplex streams on the peer connections but could be a nice feature to work with the modules of Dat project like hypercore and hyperdb.

Ok, meanwhile I'm going to use the server.js compiled on the repository.

**Comment by mattkrick** [comment]
anything i could do to help Dat progress in the wild would be worthwhile. can you share a link or a code example where it needs duplexing? my goal is to keep the node stream library out of this since it's huge & the wrtc spec allows for native multiplexing.

**Comment by tinchoz49** [comment]
For example, check the `Under the hood` section on https://docs.datproject.org/browser.

Hypercore uses an interface based on the [hypercore-protocol](https://github.com/mafintosh/hypercore-protocol) that allows you to pipe your peer connection to a `replication` duplex stream. That's is possible thanks to the stream support on [simple-peer](https://github.com/feross/simple-peer) that [https://github.com/mafintosh/webrtc-swarm](webrtc-swarm) is using under the hood.

**Comment by mattkrick** [comment]
ah shoot, it's always a bummer when protocols are written so specifically. There's no way to implement that protocol without adding some serious bloat.
If bundle size & performance is no issue, I'd just use webrtc-swarm.
If you're serious about this, you got 2 options:
- write a simple wrapper around `Uint8Array` so it has the same API as `Buffer`
- PR the protocol to handle native browser structures

IMHO, these things _should_ be using native structures. especially now that shared array buffers are so much easier. By going native you could use webworkers for large payloads, which means a smaller bundle + faster performance.

**Comment by mattkrick** [comment]
the reference implementation is now in the npm bundle at v0.1.1
it now supports audio/video, uWS, and it takes an `authorization` callback in case not everyone in the swarm has permission to talk to everyone else.
