### ISSUE TITLE
.on function not found

### ISSUE THREAD

**Issue by shd101wyy** [mattkrick/fast-rtc-swarm#2]
Hi there,

I was following the documentation but I was not able to use `swarm.on` function.

![Screenshot from 2019-10-28 00-32-54](https://user-images.githubusercontent.com/1908863/67637938-940f3000-f91a-11e9-9be7-06c6133ee213.png)

Any suggestions? 

Thank you

**Comment by mattkrick** [comment]
i think it has to do with your ts lib. it's there.
<img width="602" alt="Screen Shot 2019-10-27 at 1 12 28 PM" src="https://user-images.githubusercontent.com/5514175/67639924-8ecec880-f8bb-11e9-9152-6f71c433eefc.png">

**Comment by shd101wyy** [comment]
Weird. I changed to another computer, ran `yarn add @mattkrick/fast-rtc-swarm` again and `import` it in a javascript file. I was using visual studio code, and I still couldn't see `.on` method. Which editor are you using? Thank you.

**Comment by mattkrick** [comment]
screeenshot is from webstorm. just checked vscode & it works there for me too. make sure it's a typescript file, not javascript.

**Comment by Joery-M** [comment]
I fixed this by running `yarn add strict-event-emitter-types`, this fixed it for me.
